on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      # - name: bundle install
      #   run: bundle install
      # - name: navigating to ios
      #   run: cd ios
      # - name: Run Fastlane
      #   run: fastlane beta
      - name: Set up Ruby
        run: |
          rbenv install 3.0.2
          rbenv local 3.0.2
          gem install bundler

      - name: Deploy with Fastlane
        run: |
          # Set up Fastlane environment
          cd ios
          bundle install
          bundle exec fastlane beta

          # Run Fastlane commands (e.g., build, distribute)
          bundle exec fastlane deploy
        
